# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- fix-*
- pr-*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/PdfSharp.Xps.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      $(solution)
    arguments: '-c $(buildConfiguration) /p:Platform="$(buildPlatform)"'
    includeNuGetOrg: true
    noCache: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
      **/PDFsharpTests-GDI.sln
      **/PDFsharpTests-WPF.sln
      **/PdfSharp.Xps.UnitTests/PdfSharp-XPS.sln
    arguments: '-c $(buildConfiguration) /p:Platform="$(buildPlatform)"'
    includeNuGetOrg: true
    noCache: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    nobuild: true
    feedsToUse: 'select'
    packagesToPack: '**/PdfSharp-WPF.csproj;**/PdfSharp.Xps.csproj'
    versioningScheme: 'off'
    includeNuGetOrg: true
    noCache: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nupkg'
    publishLocation: 'Container'
