var annotated_dup =
[
    [ "PdfSharp", "namespace_pdf_sharp.html", [
      [ "Xps", "namespace_pdf_sharp_1_1_xps.html", [
        [ "Parsing", "namespace_pdf_sharp_1_1_xps_1_1_parsing.html", [
          [ "XpsParser", "class_pdf_sharp_1_1_xps_1_1_parsing_1_1_xps_parser.html", null ]
        ] ],
        [ "Rendering", "namespace_pdf_sharp_1_1_xps_1_1_rendering.html", [
          [ "BuilderBase", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_builder_base.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_builder_base" ],
          [ "DocumentRenderingContext", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_document_rendering_context.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_document_rendering_context" ],
          [ "ImageBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_image_builder.html", null ],
          [ "LinearShadingBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_linear_shading_builder.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_linear_shading_builder" ],
          [ "PatternOrShadingBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_pattern_or_shading_builder.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_pattern_or_shading_builder" ],
          [ "PdfContentWriter", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_pdf_content_writer.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_pdf_content_writer" ],
          [ "PdfRenderer", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_pdf_renderer.html", null ],
          [ "RadialShadingBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_radial_shading_builder.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_radial_shading_builder" ],
          [ "ReuseableTable", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_reuseable_table.html", null ],
          [ "TilingPatternBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_tiling_pattern_builder.html", null ],
          [ "XFormBuilder", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_form_builder.html", null ],
          [ "XPBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_brush" ],
          [ "XPCanvas", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_canvas.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_canvas" ],
          [ "XPFont", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_font.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_font" ],
          [ "XPGlyphs", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_glyphs.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_glyphs" ],
          [ "XPGradientBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_gradient_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_gradient_brush" ],
          [ "XPImage", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_image.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_image" ],
          [ "XPImageBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_image_brush.html", null ],
          [ "XPLinearGradientBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_linear_gradient_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_linear_gradient_brush" ],
          [ "XPObject", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_object.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_object" ],
          [ "XPPath", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_path.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_path" ],
          [ "XPRadialGradientBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_radial_gradient_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_radial_gradient_brush" ],
          [ "XPTilingBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_tiling_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_tiling_brush" ],
          [ "XPVisual", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_visual.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_visual" ],
          [ "XPVisualBrush", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_visual_brush.html", "class_pdf_sharp_1_1_xps_1_1_rendering_1_1_x_p_visual_brush" ]
        ] ],
        [ "XpsModel", "namespace_pdf_sharp_1_1_xps_1_1_xps_model.html", [
          [ "ArcSegment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_arc_segment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_arc_segment" ],
          [ "Brush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_brush.html", null ],
          [ "Canvas", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_canvas.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_canvas" ],
          [ "Color", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_color.html", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_color" ],
          [ "Comment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_comment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_comment" ],
          [ "Discard", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_discard.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_discard" ],
          [ "DiscardControl", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_discard_control.html", null ],
          [ "DocumentOutline", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_outline.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_outline" ],
          [ "DocumentReference", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_reference.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_reference" ],
          [ "DocumentStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_structure.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_document_structure" ],
          [ "FigureStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_figure_structure.html", null ],
          [ "FixedDocument", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document" ],
          [ "FixedDocumentCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document_collection.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document_collection" ],
          [ "FixedDocumentSequence", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document_sequence.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_document_sequence" ],
          [ "FixedPage", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_page.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_page" ],
          [ "FixedPageCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_page_collection.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_page_collection" ],
          [ "FixedPayload", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_payload.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_fixed_payload" ],
          [ "Font", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_font.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_font" ],
          [ "GlyphIndices", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_glyph_indices.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_glyph_indices" ],
          [ "GlyphIndicesParser", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_glyph_indices_parser.html", null ],
          [ "Glyphs", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_glyphs.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_glyphs" ],
          [ "GradientStop", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_gradient_stop.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_gradient_stop" ],
          [ "GradientStopCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_gradient_stop_collection.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_gradient_stop_collection" ],
          [ "ImageBrush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_image_brush.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_image_brush" ],
          [ "LinearGradientBrush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_linear_gradient_brush.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_linear_gradient_brush" ],
          [ "LinkTarget", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_link_target.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_link_target" ],
          [ "ListItemStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_list_item_structure.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_list_item_structure" ],
          [ "ListStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_list_structure.html", null ],
          [ "Matrix", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_matrix.html", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_matrix" ],
          [ "MatrixTransform", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_matrix_transform.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_matrix_transform" ],
          [ "NamedElement", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_named_element.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_named_element" ],
          [ "OutlineEntry", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_outline_entry.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_outline_entry" ],
          [ "PageContent", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_page_content.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_page_content" ],
          [ "ParagraphStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_paragraph_structure.html", null ],
          [ "PartHelper", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_part_helper.html", null ],
          [ "Path", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path" ],
          [ "PathFigure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_figure.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_figure" ],
          [ "PathFigureCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_figure_collection.html", null ],
          [ "PathGeometry", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_geometry.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_geometry" ],
          [ "PathSegment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_segment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_segment" ],
          [ "PathSegmentCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_path_segment_collection.html", null ],
          [ "Point", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_point.html", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_point" ],
          [ "PointStopCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_point_stop_collection.html", null ],
          [ "PolyBezierSegment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_bezier_segment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_bezier_segment" ],
          [ "PolyLineSegment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_line_segment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_line_segment" ],
          [ "PolyQuadraticBezierSegment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_quadratic_bezier_segment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_poly_quadratic_bezier_segment" ],
          [ "RadialGradientBrush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_radial_gradient_brush.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_radial_gradient_brush" ],
          [ "Rect", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_rect.html", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_rect" ],
          [ "ResourceDictionary", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_resource_dictionary.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_resource_dictionary" ],
          [ "SectionStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_section_structure.html", null ],
          [ "SignatureDefinition", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_signature_definition.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_signature_definition" ],
          [ "Size", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_size.html", "struct_pdf_sharp_1_1_xps_1_1_xps_model_1_1_size" ],
          [ "SolidColorBrush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_solid_color_brush.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_solid_color_brush" ],
          [ "SpotLocation", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_spot_location.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_spot_location" ],
          [ "Story", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story" ],
          [ "StoryFragment", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story_fragment.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story_fragment" ],
          [ "StoryFragmentReference", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story_fragment_reference.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_story_fragment_reference" ],
          [ "TableCellStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_table_cell_structure.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_table_cell_structure" ],
          [ "TableRowGroupStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_table_row_group_structure.html", null ],
          [ "TableRowStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_table_row_structure.html", null ],
          [ "TableStructure", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_table_structure.html", null ],
          [ "Template", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_template.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_template" ],
          [ "Visual", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_visual.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_visual" ],
          [ "VisualBrush", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_visual_brush.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_visual_brush" ],
          [ "XpsDocument", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_xps_document.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_xps_document" ],
          [ "XpsElement", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_xps_element.html", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_xps_element" ],
          [ "XpsElementCollection", "class_pdf_sharp_1_1_xps_1_1_xps_model_1_1_xps_element_collection.html", null ]
        ] ],
        [ "XpsConverter", "class_pdf_sharp_1_1_xps_1_1_xps_converter.html", "class_pdf_sharp_1_1_xps_1_1_xps_converter" ]
      ] ]
    ] ]
];