H:\DL\fart.exe -r -- *.cs "using Microsoft.VisualStudio.TestTools.UnitTesting;" "using NUnit.Framework;"    
H:\DL\fart.exe -r --remove -- *.cs "[TestClass]"
H:\DL\fart.exe -r -- *.cs "[TestInitialize()]" "[SetUp]"
H:\DL\fart.exe -r -- *.cs "[TestInitialize]" "[SetUp]"
H:\DL\fart.exe -r -- *.cs "[TestCleanup()]" "[TearDown]"
H:\DL\fart.exe -r -- *.cs "[TestCleanup]" "[TearDown]"
H:\DL\fart.exe -r -- *.cs "[TestMethod]" "[Test]"
H:\DL\fart.exe -r -- *.cs "[ClassInitialize()]" "[OneTimeSetUp]"
H:\DL\fart.exe -r -- *.cs "[ClassCleanup()]" "[OneTimeTearDown]"
